### ISSUE TITLE
termux-torch crashes Termux:API on Android 5.0.1

### ISSUE THREAD

**Issue by benburrill** [termux/termux-api#188]
logcat shows the error `java.lang.NoSuchMethodError: No virtual method setTorchMode`.  The method was added in API level 23, which I don't have.

There are more compatible ways of enabling torch mode.  I currently use the [Torch](https://github.com/MrDoomy/Torch) app, which uses the deprecated `Camera.Parameters` API, which maybe Termux:API could use as a fallback.

**Comment by dkramer95** [comment]
@benburrill #189 should fix this... I don't have a physical device running lollipop to test, but works in emulator running 5.0... The emulator doesn't have a virtual LED flash display, but it should be good!

**Comment by benburrill** [comment]
I can confirm that it now works on 5.0.1 so I'm closing the issue.
Somewhat unrelated question, but is there currently any way to determine whether the torch is already on?  Ultimately I'd like to be able to toggle it, not just turn it on/off.
